import os
import unittest

from data import *
from explore.stat import statError
from hydroDL.master import *
from utils import hydro_util
from visual import *
import numpy as np
import definitions


class MyTestCaseGages(unittest.TestCase):
    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        self.config_file = os.path.join(config_dir, "basic/config_ex1.ini")
        self.subdir = r"basic/exp1"

    def test_gages_train(self):
        print('Starting ...')
        config_data = GagesConfig.set_subdir(self.config_file, self.subdir)
        # 准备训练数据
        source_data = GagesSource(config_data, config_data.model_dict["data"]["tRangeTrain"])
        # 构建输入数据类对象
        data_model = DataModel(source_data)
        # 进行模型训练
        # train model
        master_train(data_model)


if __name__ == '__main__':
    unittest.main()
