import os
import unittest

import definitions
from data import GagesConfig, GagesSource, DataModel
from hydroDL import master_train


class MyTestCase(unittest.TestCase):
    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        self.config_file = os.path.join(config_dir, "smallres/config_smallres_ex4.ini")
        self.subdir = r"smallres/exp4"

    def test_some_reservoirs(self):
        """choose some small reservoirs randomly to train and test"""
        # 读取模型配置文件
        config_data = GagesConfig.set_subdir(self.config_file, self.subdir)
        # choose some small basins, unit: SQKM
        basin_area_screen = 100
        source_data = GagesSource.choose_some_basins(config_data, config_data.model_dict["data"]["tRangeTrain"],
                                                     basin_area_screen)
        # 构建输入数据类对象
        data_model = DataModel(source_data)
        # train model
        master_train(data_model)


if __name__ == '__main__':
    unittest.main()
