import unittest

import definitions
from data import GagesConfig, GagesSource, DataModel
from data.data_config import add_model_param
from data.data_input import save_datamodel, load_datamodel
from data.gages_input_dataset import GagesInvDataModel, GagesDaDataModel
from explore.stat import statError
from hydroDL.master.master import train_lstm_da, test_lstm_da
import numpy as np
import os
import pandas as pd
from utils.dataset_format import subset_of_dict
from visual import plot_ts_obs_pred
from visual.plot_model import plot_boxes_inds, plot_ind_map


class MyTestCase(unittest.TestCase):
    """historical data assimilation"""

    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        # self.config_file = os.path.join(config_dir, "da/config_da_exp1.ini")
        # self.subdir = r"da/exp1"
        self.config_file = os.path.join(config_dir, "da/config_da_exp2.ini")
        self.subdir = r"da/exp2"
        self.config_data = GagesConfig.set_subdir(self.config_file, self.subdir)
        add_model_param(self.config_data, "model", seqLength=7)
        # choose some small basins, unit: SQKM
        self.basin_area_screen = 100

    def test_da_data_temp(self):
        config_data = self.config_data
        source_data = GagesSource(config_data, config_data.model_dict["data"]["tRangeTrain"])
        df = DataModel(source_data)
        save_datamodel(df, data_source_file_name='data_source.txt',
                       stat_file_name='Statistics.json', flow_file_name='flow', forcing_file_name='forcing',
                       attr_file_name='attr', f_dict_file_name='dictFactorize.json',
                       var_dict_file_name='dictAttribute.json', t_s_dict_file_name='dictTimeSpace.json')

    def test_da_train(self):
        df = load_datamodel(self.config_data.data_path["Temp"], data_source_file_name='data_source.txt',
                            stat_file_name='Statistics.json', flow_file_name='flow.npy',
                            forcing_file_name='forcing.npy', attr_file_name='attr.npy',
                            f_dict_file_name='dictFactorize.json',
                            var_dict_file_name='dictAttribute.json',
                            t_s_dict_file_name='dictTimeSpace.json')
        data_model = GagesDaDataModel(df)
        train_lstm_da(data_model)

    def test_da_data_temp_test(self):
        config_data = self.config_data
        source_data = GagesSource(config_data, config_data.model_dict["data"]["tRangeTest"])
        df = DataModel(source_data)
        save_datamodel(df, data_source_file_name='test_data_source.txt',
                       stat_file_name='test_Statistics.json', flow_file_name='test_flow',
                       forcing_file_name='test_forcing', attr_file_name='test_attr',
                       f_dict_file_name='test_dictFactorize.json', var_dict_file_name='test_dictAttribute.json',
                       t_s_dict_file_name='test_dictTimeSpace.json')

    def test_da_test(self):
        df1 = load_datamodel(self.config_data.data_path["Temp"], data_source_file_name='test_data_source.txt',
                             stat_file_name='test_Statistics.json', flow_file_name='test_flow.npy',
                             forcing_file_name='test_forcing.npy', attr_file_name='test_attr.npy',
                             f_dict_file_name='test_dictFactorize.json',
                             var_dict_file_name='test_dictAttribute.json',
                             t_s_dict_file_name='test_dictTimeSpace.json')

        data_model = GagesDaDataModel(df1)
        pred, obs = test_lstm_da(data_model)

        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(obs.shape[0], obs.shape[1])

        inds = statError(obs, pred)
        show_me_num = 5
        t_s_dict = data_model.data_model.t_s_dict
        sites = np.array(t_s_dict["sites_id"])
        t_range = np.array(t_s_dict["t_final_range"])
        time_seq_length = data_model.data_model.data_source.data_config.model_dict['model']['seqLength']
        time_start = np.datetime64(t_range[0]) + np.timedelta64(time_seq_length, 'D')
        t_range[0] = np.datetime_as_string(time_start, unit='D')
        ts_fig = plot_ts_obs_pred(obs, pred, sites, t_range, show_me_num)
        ts_fig.savefig(os.path.join(self.config_data.data_path["Out"], "ts_fig.png"))
        # # plot box，使用seaborn库
        keys = ["Bias", "RMSE", "NSE"]
        inds_test = subset_of_dict(inds, keys)
        box_fig = plot_boxes_inds(inds_test)
        box_fig.savefig(os.path.join(self.config_data.data_path["Out"], "box_fig.png"))
        # plot map
        sites_df = pd.DataFrame({"sites": sites, keys[2]: inds_test[keys[2]]})
        plot_ind_map(df1.data_source.all_configs['gage_point_file'], sites_df)

    def test_inv_data_temp_smallres(self):
        config_data_1 = self.config_data
        source_data_1 = GagesSource.choose_some_basins(config_data_1, config_data_1.model_dict["data"]["tRangeTrain"],
                                                       self.basin_area_screen)
        df1 = DataModel(source_data_1)
        save_datamodel(df1, data_source_file_name='data_source.txt',
                       stat_file_name='Statistics.json', flow_file_name='flow', forcing_file_name='forcing',
                       attr_file_name='attr', f_dict_file_name='dictFactorize.json',
                       var_dict_file_name='dictAttribute.json', t_s_dict_file_name='dictTimeSpace.json')

    def test_inv_data_temp_test_smallres(self):
        config_data_1 = self.config_data
        source_data_1 = GagesSource.choose_some_basins(config_data_1, config_data_1.model_dict["data"]["tRangeTest"],
                                                       self.basin_area_screen)
        df1 = DataModel(source_data_1)
        save_datamodel(df1, data_source_file_name='test_data_source.txt',
                       stat_file_name='test_Statistics.json', flow_file_name='test_flow',
                       forcing_file_name='test_forcing', attr_file_name='test_attr',
                       f_dict_file_name='test_dictFactorize.json', var_dict_file_name='test_dictAttribute.json',
                       t_s_dict_file_name='test_dictTimeSpace.json')


if __name__ == '__main__':
    unittest.main()
