import os
import unittest

import definitions
from data.sim_nature_flow_config import SimNatureFlowConfig
from hydroDL.model import model_run




class MyTestCase(unittest.TestCase):
    def test_natural_flow_in(self):
        """using natural flow generated by model trained by choosed allref basins in CAMELS dataset"""
        config_dir = definitions.CONFIG_DIR
        config_file = os.path.join(config_dir, "config_natureflow.ini")
        config_data = SimNatureFlowConfig(config_file)
        out_folder = config_data.data_path["Out"]
        epoch = config_data.model_dict["train"]["nEpoch"]
        source_data = SimNatureFlowSource(config_data, config_data.model_dict["data"]["tRangeTrain"])
        dataModel = DataModel(source_data)
        model = model_run.model_load(out_folder, epoch, model_name='model')
        file_path = 1
        batch_size = 1
        x = 1
        c = 1
        natural_flow = model_run.model_test(model, x, c, file_path=file_path, batch_size=batch_size)
        hydroDL.master_train(data_model)


if __name__ == '__main__':
    unittest.main()
