import os
import unittest

import definitions
from data import GagesConfig
from data.gages_input_dataset import GagesSourceDataset, GagesInputDataset
from hydroDL.master.master import train_stacked_lstm


class MyTestCase(unittest.TestCase):
    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        self.config_file = os.path.join(config_dir, "config_stackedlstm.ini")

    def test_stacked_lstm(self):
        """try to input data from nonref regions to a stacked lstm to see what will happen"""
        config_file = self.config_file
        # 读取模型配置文件
        config_data = GagesConfig(config_file)
        # 准备训练数据
        source_data = GagesSourceDataset(config_data, config_data.model_dict["data"]["tRangeTrain"])
        # 构建输入数据类对象
        data_model = GagesInputDataset(source_data)
        # 进行模型训练
        # train model
        train_stacked_lstm(data_model)


if __name__ == '__main__':
    unittest.main()
