name: hydrodl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - geopandas
  - cartopy
  - scikit-learn>=0.23.0
  - pandas
  - seaborn
  - future
  - h5py
  - pyyaml
  - plotly~=4.14.3
  - pytz~=2021.1
  - numpy~=1.20.1
  - requests~=2.25.1
  - mpld3~=0.3
  - numba>=0.50
  - openpyxl
  - pip
  - pip:
    - setuptools~=56.0.0
    - torch
    - torchvision>=0.6.0
    - tb-nightly
    - shap~=0.39.0
    - sphinx
    - sphinx-rtd-theme
    - sphinx-autodoc-typehints