name: SPDB
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23
  - xarray
  - geopandas
  - cartopy
  - seaborn
  - scikit-learn
  - tqdm
  - hydroerr
  - pytorch=1.12
  - pytorch-scatter
  - tensorboard
  - torchvision
  - pytest
  - black
  - flake8
  - ipykernel
  - pip
  - pip:
    - tbparse
