name: SPDB
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cudatoolkit=10.0
  - pydrive=1.3.1
  - geopandas=0.6.3
  - netcdf4=1.5.3
  - scipy=1.4.1
  - tensorboard=1.15.0
  - future=0.18.2
  - matplotlib=3.1.3
  - statsmodels=0.11.0
  - seaborn=0.10.0
  - cartopy=0.17.0
  - geoplot=0.4.0
  - easydict
  - pyarrow
  - xlrd
