import unittest

from functools import reduce
import definitions
from data import GagesConfig, GagesSource, DataModel
from data.data_input import save_datamodel, GagesModel, _basin_norm, save_result, load_result
from data.gages_input_dataset import GagesDamDataModel, GagesModels, choose_which_purpose, load_dataconfig_case_exp
from data.nid_input import NidModel, save_nidinput
from explore.gages_stat import split_results_to_regions
from explore.stat import statError, ecdf
from hydroDL.master.master import master_train, master_test
import numpy as np
import os
import pandas as pd

from utils import serialize_json, unserialize_json
from utils.dataset_format import subset_of_dict
from visual import plot_ts_obs_pred
from visual.plot_model import plot_ind_map, plot_we_need, plot_map
from visual.plot_stat import plot_ecdf, plot_diff_boxes, plot_ecdfs


class MyTestCase(unittest.TestCase):
    """data pre-process and post-process"""

    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        self.config_file = os.path.join(config_dir, "basic/config_exp23.ini")
        self.subdir = r"basic/exp23"
        self.config_data = GagesConfig.set_subdir(self.config_file, self.subdir)
        # self.nid_file = 'PA_U.xlsx'
        # self.nid_file = 'OH_U.xlsx'
        self.nid_file = 'NID2018_U.xlsx'
        self.test_epoch = 300

    def test_diversion_pooling_seperate_cases(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]

        diversion_yes = True
        diversion_no = False
        source_data_diversion = GagesSource.choose_some_basins(self.config_data,
                                                               self.config_data.model_dict["data"]["tRangeTrain"],
                                                               screen_basin_area_huc4=False,
                                                               diversion=diversion_yes)
        source_data_nodivert = GagesSource.choose_some_basins(self.config_data,
                                                              self.config_data.model_dict["data"]["tRangeTrain"],
                                                              screen_basin_area_huc4=False,
                                                              diversion=diversion_no)
        sites_id_nodivert = source_data_nodivert.all_configs['flow_screen_gage_id']
        sites_id_diversion = source_data_diversion.all_configs['flow_screen_gage_id']

        idx_lst_nodivert = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_nodivert]
        idx_lst_diversion = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_diversion]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["no_diversion_together", "diversion_together"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_nodivert])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_diversion])
        xs.append(x2)
        ys.append(y2)

        cases_exps = ["diversion_exp2", "diversion_exp1"]
        cases_exps_legends_separate = ["no_diversion_separate", "diversion_separate"]
        for case_exp in cases_exps:
            config_data_i = load_dataconfig_case_exp(case_exp)
            pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
            pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
            obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
            inds_i = statError(obs_i, pred_i)
            x, y = ecdf(inds_i[keys_nse])
            xs.append(x)
            ys.append(y)

        plot_ecdfs(xs, ys, cases_exps_legends_together + cases_exps_legends_separate)

    def test_diversion_small_dor_pooling_cases(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]

        diversion_no = False
        source_data_nodivert = GagesSource.choose_some_basins(self.config_data,
                                                              self.config_data.model_dict["data"]["tRangeTrain"],
                                                              screen_basin_area_huc4=False,
                                                              diversion=diversion_no)
        sites_id_nodivert = source_data_nodivert.all_configs['flow_screen_gage_id']

        dor_1 = - 0.02
        source_data_dor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_1)
        sites_id_dor1 = source_data_dor1.all_configs['flow_screen_gage_id']

        no_divert_small_dor = np.intersect1d(sites_id_nodivert, sites_id_dor1)

        idx_lst_nodivert_smalldor = [i for i in range(len(all_sites)) if all_sites[i] in no_divert_small_dor]
        idx_lst_smalldor = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_dor1]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["not_diverted_small_dor", "small_dor"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_nodivert_smalldor])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_smalldor])
        xs.append(x2)
        ys.append(y2)

        plot_ecdfs(xs, ys, cases_exps_legends_together)

    def test_diversion_dor_pooling_cases(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]

        diversion_yes = True
        diversion_no = False
        source_data_diversion = GagesSource.choose_some_basins(self.config_data,
                                                               self.config_data.model_dict["data"]["tRangeTrain"],
                                                               screen_basin_area_huc4=False,
                                                               diversion=diversion_yes)
        source_data_nodivert = GagesSource.choose_some_basins(self.config_data,
                                                              self.config_data.model_dict["data"]["tRangeTrain"],
                                                              screen_basin_area_huc4=False,
                                                              diversion=diversion_no)
        sites_id_nodivert = source_data_nodivert.all_configs['flow_screen_gage_id']
        sites_id_diversion = source_data_diversion.all_configs['flow_screen_gage_id']

        dor_1 = - 0.02
        dor_2 = 0.02
        source_data_dor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_1)
        source_data_dor2 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_2)
        sites_id_dor1 = source_data_dor1.all_configs['flow_screen_gage_id']
        sites_id_dor2 = source_data_dor2.all_configs['flow_screen_gage_id']

        no_divert_small_dor = np.intersect1d(sites_id_nodivert, sites_id_dor1)
        no_divert_large_dor = np.intersect1d(sites_id_nodivert, sites_id_dor2)
        diversion_small_dor = np.intersect1d(sites_id_diversion, sites_id_dor1)
        diversion_large_dor = np.intersect1d(sites_id_diversion, sites_id_dor2)

        idx_lst_nodivert_smalldor = [i for i in range(len(all_sites)) if all_sites[i] in no_divert_small_dor]
        idx_lst_nodivert_largedor = [i for i in range(len(all_sites)) if all_sites[i] in no_divert_large_dor]
        idx_lst_diversion_smalldor = [i for i in range(len(all_sites)) if all_sites[i] in diversion_small_dor]
        idx_lst_diversion_largedor = [i for i in range(len(all_sites)) if all_sites[i] in diversion_large_dor]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["not_diverted_small_dor", "not_diverted_large_dor", "diversion_small_dor",
                                       "diversion_large_dor"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_nodivert_smalldor])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_nodivert_largedor])
        xs.append(x2)
        ys.append(y2)

        x3, y3 = ecdf(inds_df[keys_nse].iloc[idx_lst_diversion_smalldor])
        xs.append(x3)
        ys.append(y3)

        x4, y4 = ecdf(inds_df[keys_nse].iloc[idx_lst_diversion_largedor])
        xs.append(x4)
        ys.append(y4)

        plot_ecdfs(xs, ys, cases_exps_legends_together)

    def test_export_result(self):
        # data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
        #                                        data_source_file_name='test_data_source.txt',
        #                                        stat_file_name='test_Statistics.json', flow_file_name='test_flow.npy',
        #                                        forcing_file_name='test_forcing.npy', attr_file_name='test_attr.npy',
        #                                        f_dict_file_name='test_dictFactorize.json',
        #                                        var_dict_file_name='test_dictAttribute.json',
        #                                        t_s_dict_file_name='test_dictTimeSpace.json')

        config_dir = definitions.CONFIG_DIR
        # camels_config_file = os.path.join(config_dir, "basic/config_exp1.ini")
        # camels_subdir = r"basic/exp1"
        # camels_config_data = GagesConfig.set_subdir(camels_config_file, camels_subdir)
        # data_model = GagesModel.load_datamodel(camels_config_data.data_path["Temp"],
        #                                        data_source_file_name='test_data_source.txt',
        #                                        stat_file_name='test_Statistics.json',
        #                                        flow_file_name='test_flow.npy',
        #                                        forcing_file_name='test_forcing.npy',
        #                                        attr_file_name='test_attr.npy',
        #                                        f_dict_file_name='test_dictFactorize.json',
        #                                        var_dict_file_name='test_dictAttribute.json',
        #                                        t_s_dict_file_name='test_dictTimeSpace.json')

        # config_file = os.path.join(config_dir, "nodam/config_exp3.ini")
        # subdir = r"nodam/exp3"
        config_file = os.path.join(config_dir, "majordam/config_exp2.ini")
        subdir = r"majordam/exp2"
        config_data = GagesConfig.set_subdir(config_file, subdir)
        data_model = GagesModel.load_datamodel(config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(obs.shape[0], obs.shape[1])
        inds = statError(obs, pred)
        inds['STAID'] = data_model.t_s_dict["sites_id"]
        inds_df = pd.DataFrame(inds)
        print(inds_df.median())

        # inds_df.to_csv(os.path.join(self.config_data.data_path["Out"], 'data_df.csv'))

    def test_camels_dataset(self):
        config_dir = definitions.CONFIG_DIR
        camels_config_file = os.path.join(config_dir, "basic/config_exp1.ini")
        camels_subdir = r"basic/exp1"
        camels_config_data = GagesConfig.set_subdir(camels_config_file, camels_subdir)
        camels_data_model = GagesModel.load_datamodel(camels_config_data.data_path["Temp"],
                                                      data_source_file_name='test_data_source.txt',
                                                      stat_file_name='test_Statistics.json',
                                                      flow_file_name='test_flow.npy',
                                                      forcing_file_name='test_forcing.npy',
                                                      attr_file_name='test_attr.npy',
                                                      f_dict_file_name='test_dictFactorize.json',
                                                      var_dict_file_name='test_dictAttribute.json',
                                                      t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites_camels = camels_data_model.t_s_dict["sites_id"]
        dor_1 = - 0.02
        dor_2 = 0.02
        source_data_dor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_1)
        source_data_dor2 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_2)
        sites_id_dor1 = source_data_dor1.all_configs['flow_screen_gage_id']
        sites_id_dor2 = source_data_dor2.all_configs['flow_screen_gage_id']
        print(np.intersect1d(all_sites_camels, sites_id_dor1))
        print(np.intersect1d(all_sites_camels, sites_id_dor2))

    def test_plot_ecdf_together(self):
        xs = []
        ys = []
        # cases_exps = ["basic_exp21", "basic_exp22", "basic_exp23", "basic_exp24"]
        # cases_exps_legends = ["miniBatch = [100, 200]	hiddenSize = 256",
        #                       "miniBatch = [100, 100]	hiddenSize = 256",
        #                       "miniBatch = [100, 365]	hiddenSize = 256",
        #                       "miniBatch = [100, 365]	hiddenSize = 128"]
        cases_exps = ["basic_exp19", "basic_exp20", "basic_exp23", "basic_exp25"]
        cases_exps_legends = ["attr19", "attr20", "attr23", "attr25"]
        for case_exp in cases_exps:
            config_data_i = load_dataconfig_case_exp(case_exp)
            pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
            pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
            obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
            inds_i = statError(obs_i, pred_i)
            x, y = ecdf(inds_i["NSE"])
            xs.append(x)
            ys.append(y)
        plot_ecdfs(xs, ys, cases_exps_legends)

    def test_multi_cases_in_one_exp_stat_together(self):
        experiment = "ecoregion_exp1"
        cases = ["5.2", "5.3", "6.2", "7.1", "8.1", "8.2", "8.3", "8.4", "8.5", "9.2", "9.3", "9.4", "9.5",
                 "9.6", "10.1", "10.2", "10.4", "11.1", "12.1", "13.1"]
        pred = []
        obs = []
        config_data_i = load_dataconfig_case_exp(experiment)
        for case in cases:
            temp_dir = os.path.join(config_data_i.data_path['Temp'], case)
            pred_i, obs_i = load_result(temp_dir, self.test_epoch)
            pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
            obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
            pred.append(pred_i)
            obs.append(obs_i)
        pred_stack = reduce(lambda a, b: np.vstack((a, b)),
                            list(map(lambda x: x.reshape(x.shape[0], x.shape[1]), pred)))
        obs_stack = reduce(lambda a, b: np.vstack((a, b)),
                           list(map(lambda x: x.reshape(x.shape[0], x.shape[1]), obs)))
        inds = statError(obs_stack, pred_stack)
        inds_df = pd.DataFrame(inds)
        print(inds_df.median(axis=0))
        print(inds_df.mean(axis=0))

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends = ["separate", "together"]

        x1, y1 = ecdf(inds_df[keys_nse])
        xs.append(x1)
        ys.append(y1)

        pooling_experiment = "basic_exp23"
        config_data_pooling = load_dataconfig_case_exp(pooling_experiment)
        pred, obs = load_result(config_data_pooling.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds_pooling = statError(obs, pred)
        inds_pooling_df = pd.DataFrame(inds_pooling)
        x2, y2 = ecdf(inds_pooling_df[keys_nse])
        xs.append(x2)
        ys.append(y2)
        plot_ecdfs(xs, ys, cases_exps_legends)

    def test_multi_cases_stat_together(self):
        cases_exps = ["basic_exp14", "basic_exp15", "basic_exp2", "basic_exp3", "basic_exp4",
                      "basic_exp5", "basic_exp6", "basic_exp7", "basic_exp8", "basic_exp9"]
        pred = []
        obs = []
        for case_exp in cases_exps:
            config_data_i = load_dataconfig_case_exp(case_exp)
            pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
            pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
            obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
            pred.append(pred_i)
            obs.append(obs_i)
        pred_stack = reduce(lambda a, b: np.vstack((a, b)),
                            list(map(lambda x: x.reshape(x.shape[0], x.shape[1]), pred)))
        obs_stack = reduce(lambda a, b: np.vstack((a, b)),
                           list(map(lambda x: x.reshape(x.shape[0], x.shape[1]), obs)))
        inds = statError(obs_stack, pred_stack)
        inds_df = pd.DataFrame(inds)
        print(inds_df.median(axis=0))
        print(inds_df.mean(axis=0))

    def test_purposes_seperate(self):
        quick_data_dir = os.path.join(self.config_data.data_path["DB"], "quickdata")
        data_dir = os.path.join(quick_data_dir, "conus-all_90-10_nan-0.0_00-1.0")
        data_model_test = GagesModel.load_datamodel(data_dir,
                                                    data_source_file_name='test_data_source.txt',
                                                    stat_file_name='test_Statistics.json',
                                                    flow_file_name='test_flow.npy',
                                                    forcing_file_name='test_forcing.npy',
                                                    attr_file_name='test_attr.npy',
                                                    f_dict_file_name='test_dictFactorize.json',
                                                    var_dict_file_name='test_dictAttribute.json',
                                                    t_s_dict_file_name='test_dictTimeSpace.json')
        data_model = GagesModel.update_data_model(self.config_data, data_model_test)
        nid_dir = os.path.join("/".join(self.config_data.data_path["DB"].split("/")[:-1]), "nid", "quickdata")
        gage_main_dam_purpose = unserialize_json(os.path.join(nid_dir, "dam_main_purpose_dict.json"))
        gage_main_dam_purpose_lst = list(gage_main_dam_purpose.values())
        gage_main_dam_purpose_unique = np.unique(gage_main_dam_purpose_lst)
        purpose_regions = {}
        for i in range(gage_main_dam_purpose_unique.size):
            sites_id = []
            for key, value in gage_main_dam_purpose.items():
                if value == gage_main_dam_purpose_unique[i]:
                    sites_id.append(key)
            assert (all(x < y for x, y in zip(sites_id, sites_id[1:])))
            purpose_regions[gage_main_dam_purpose_unique[i]] = sites_id
        id_regions_idx = []
        id_regions_sites_ids = []
        df_id_region = np.array(data_model.t_s_dict["sites_id"])
        for key, value in purpose_regions.items():
            gages_id = value
            c, ind1, ind2 = np.intersect1d(df_id_region, gages_id, return_indices=True)
            assert (all(x < y for x, y in zip(ind1, ind1[1:])))
            assert (all(x < y for x, y in zip(c, c[1:])))
            id_regions_idx.append(ind1)
            id_regions_sites_ids.append(c)
        pred_all, obs_all = load_result(self.config_data.data_path["Temp"], self.test_epoch)
        pred_all = pred_all.reshape(pred_all.shape[0], pred_all.shape[1])
        obs_all = obs_all.reshape(obs_all.shape[0], obs_all.shape[1])
        for i in range(9, len(gage_main_dam_purpose_unique)):
            pred = pred_all[id_regions_idx[i], :]
            obs = obs_all[id_regions_idx[i], :]
            inds = statError(obs, pred)
            inds['STAID'] = id_regions_sites_ids[i]
            inds_df = pd.DataFrame(inds)
            inds_df.to_csv(os.path.join(self.config_data.data_path["Out"],
                                        gage_main_dam_purpose_unique[i] + "epoch" + str(
                                            self.test_epoch) + 'data_df.csv'))
            # plot box，使用seaborn库
            keys = ["Bias", "RMSE", "NSE"]
            inds_test = subset_of_dict(inds, keys)
            box_fig = plot_diff_boxes(inds_test)
            box_fig.savefig(os.path.join(self.config_data.data_path["Out"],
                                         gage_main_dam_purpose_unique[i] + "epoch" + str(
                                             self.test_epoch) + "box_fig.png"))
            # plot ts
            sites = np.array(df_id_region[id_regions_idx[i]])
            t_range = np.array(data_model.t_s_dict["t_final_range"])
            show_me_num = 1
            ts_fig = plot_ts_obs_pred(obs, pred, sites, t_range, show_me_num)
            ts_fig.savefig(os.path.join(self.config_data.data_path["Out"],
                                        gage_main_dam_purpose_unique[i] + "epoch" + str(
                                            self.test_epoch) + "ts_fig.png"))
            # plot nse ecdf
            sites_df_nse = pd.DataFrame({"sites": sites, keys[2]: inds_test[keys[2]]})
            plot_ecdf(sites_df_nse, keys[2], os.path.join(self.config_data.data_path["Out"],
                                                          gage_main_dam_purpose_unique[i] + "epoch" + str(
                                                              self.test_epoch) + "ecdf_fig.png"))
            # plot map
            gauge_dict = data_model.data_source.gage_dict
            save_map_file = os.path.join(self.config_data.data_path["Out"],
                                         gage_main_dam_purpose_unique[i] + "epoch" + str(
                                             self.test_epoch) + "map_fig.png")
            plot_map(gauge_dict, sites_df_nse, save_file=save_map_file, id_col="STAID", lon_col="LNG_GAGE",
                     lat_col="LAT_GAGE")

    def test_purposes_inds(self):
        quick_data_dir = os.path.join(self.config_data.data_path["DB"], "quickdata")
        data_dir = os.path.join(quick_data_dir, "allnonref-dam_95-05_nan-0.1_00-1.0")
        data_model = GagesModel.load_datamodel(data_dir,
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        gages_data_model = GagesModel.update_data_model(self.config_data, data_model)
        nid_dir = os.path.join("/".join(self.config_data.data_path["DB"].split("/")[:-1]), "nid", "quickdata")
        gage_main_dam_purpose = unserialize_json(os.path.join(nid_dir, "dam_main_purpose_dict.json"))
        gage_main_dam_purpose_lst = list(gage_main_dam_purpose.values())
        gage_main_dam_purpose_unique = np.unique(gage_main_dam_purpose_lst)
        purpose_regions = {}
        for i in range(gage_main_dam_purpose_unique.size):
            sites_id = []
            for key, value in gage_main_dam_purpose.items():
                if value == gage_main_dam_purpose_unique[i]:
                    sites_id.append(key)
            assert (all(x < y for x, y in zip(sites_id, sites_id[1:])))
            purpose_regions[gage_main_dam_purpose_unique[i]] = sites_id
        id_regions_idx = []
        id_regions_sites_ids = []
        df_id_region = np.array(gages_data_model.t_s_dict["sites_id"])
        for key, value in purpose_regions.items():
            gages_id = value
            c, ind1, ind2 = np.intersect1d(df_id_region, gages_id, return_indices=True)
            assert (all(x < y for x, y in zip(ind1, ind1[1:])))
            assert (all(x < y for x, y in zip(c, c[1:])))
            id_regions_idx.append(ind1)
            id_regions_sites_ids.append(c)
        preds, obss, inds_dfs = split_results_to_regions(gages_data_model, self.test_epoch, id_regions_idx,
                                                         id_regions_sites_ids)
        region_names = list(purpose_regions.keys())
        inds_medians = []
        inds_means = []
        for i in range(len(region_names)):
            inds_medians.append(inds_dfs[i].median(axis=0))
            inds_means.append(inds_dfs[i].mean(axis=0))
        print(inds_medians)
        print(inds_means)

    def test_comp_same_dor_sim_or_basic_cases(self):
        dam_experiment1 = "dam_exp11"
        dam_experiment2 = "dam_exp12"
        config_data_dam1 = load_dataconfig_case_exp(dam_experiment1)
        data_model_dam1 = GagesModel.load_datamodel(config_data_dam1.data_path["Temp"],
                                                    data_source_file_name='test_data_source.txt',
                                                    stat_file_name='test_Statistics.json',
                                                    flow_file_name='test_flow.npy',
                                                    forcing_file_name='test_forcing.npy',
                                                    attr_file_name='test_attr.npy',
                                                    f_dict_file_name='test_dictFactorize.json',
                                                    var_dict_file_name='test_dictAttribute.json',
                                                    t_s_dict_file_name='test_dictTimeSpace.json')
        config_data_dam2 = load_dataconfig_case_exp(dam_experiment2)
        data_model_dam2 = GagesModel.load_datamodel(config_data_dam2.data_path["Temp"],
                                                    data_source_file_name='test_data_source.txt',
                                                    stat_file_name='test_Statistics.json',
                                                    flow_file_name='test_flow.npy',
                                                    forcing_file_name='test_forcing.npy',
                                                    attr_file_name='test_attr.npy',
                                                    f_dict_file_name='test_dictFactorize.json',
                                                    var_dict_file_name='test_dictAttribute.json',
                                                    t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites_dam1 = data_model_dam1.t_s_dict["sites_id"]
        all_sites_dam2 = data_model_dam2.t_s_dict["sites_id"]
        dor_1 = - 0.02
        dor_2 = 0.02
        source_data_dor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_1)
        source_data_dor2 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_2)
        sites_id_dor1 = source_data_dor1.all_configs['flow_screen_gage_id']
        sites_id_dor2 = source_data_dor2.all_configs['flow_screen_gage_id']

        source_data_nomajordam = GagesSource.choose_some_basins(self.config_data,
                                                                self.config_data.model_dict["data"]["tRangeTrain"],
                                                                screen_basin_area_huc4=False,
                                                                major_dam_num=0)
        sites_id_nomajordam = source_data_nomajordam.all_configs['flow_screen_gage_id']
        idx_lst_dor1 = [i for i in range(len(all_sites_dam1)) if
                        all_sites_dam1[i] in sites_id_dor1 and all_sites_dam1[i] not in sites_id_nomajordam]
        idx_lst_dor2 = [i for i in range(len(all_sites_dam2)) if
                        all_sites_dam2[i] in sites_id_dor2 and all_sites_dam2[i] not in sites_id_nomajordam]

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together1 = ["small_dor_major_dam", "small_dor_major_dam_natflow"]
        cases_exps_legends_together2 = ["large_dor_major_dam", "large_dor_major_dam_natflow"]

        pred_dam1, obs_dam1 = load_result(config_data_dam1.data_path['Temp'], self.test_epoch)
        pred_dam1 = pred_dam1.reshape(pred_dam1.shape[0], pred_dam1.shape[1])
        obs_dam1 = obs_dam1.reshape(pred_dam1.shape[0], pred_dam1.shape[1])
        inds_dam1 = statError(obs_dam1, pred_dam1)
        inds_dam1_df = pd.DataFrame(inds_dam1)
        x1, y1 = ecdf(inds_dam1_df[keys_nse].iloc[idx_lst_dor1])
        xs.append(x1)
        ys.append(y1)

        natflow_experiment1 = "simulate_exp3"
        config_data_natflow1 = load_dataconfig_case_exp(natflow_experiment1)
        pred1, obs1 = load_result(config_data_natflow1.data_path['Temp'], self.test_epoch)
        pred1 = pred1.reshape(pred1.shape[0], pred1.shape[1])
        obs1 = obs1.reshape(pred1.shape[0], pred1.shape[1])
        inds1 = statError(obs1, pred1)
        inds1_df = pd.DataFrame(inds1)
        x11, y11 = ecdf(inds1_df[keys_nse])
        xs.append(x11)
        ys.append(y11)

        pred_dam2, obs_dam2 = load_result(config_data_dam2.data_path['Temp'], self.test_epoch)
        pred_dam2 = pred_dam2.reshape(pred_dam2.shape[0], pred_dam2.shape[1])
        obs_dam2 = obs_dam2.reshape(pred_dam2.shape[0], pred_dam2.shape[1])
        inds_dam2 = statError(obs_dam2, pred_dam2)
        inds_dam2_df = pd.DataFrame(inds_dam2)
        x2, y2 = ecdf(inds_dam2_df[keys_nse].iloc[idx_lst_dor2])
        xs.append(x2)
        ys.append(y2)

        natflow_experiment2 = "simulate_exp4"
        config_data_natflow2 = load_dataconfig_case_exp(natflow_experiment2)
        pred2, obs2 = load_result(config_data_natflow2.data_path['Temp'], self.test_epoch)
        pred2 = pred2.reshape(pred2.shape[0], pred2.shape[1])
        obs2 = obs2.reshape(pred2.shape[0], pred2.shape[1])
        inds2 = statError(obs2, pred2)
        inds2_df = pd.DataFrame(inds2)
        x22, y22 = ecdf(inds2_df[keys_nse])
        xs.append(x22)
        ys.append(y22)

        plot_ecdfs(xs, ys, cases_exps_legends_together1 + cases_exps_legends_together2)

    def test_w_wo_majordam_pooling_seperate_cases(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]
        majordam_num1 = 0
        majordam_num2 = [1, 200]
        source_data_nomajordam = GagesSource.choose_some_basins(self.config_data,
                                                                self.config_data.model_dict["data"]["tRangeTrain"],
                                                                screen_basin_area_huc4=False,
                                                                major_dam_num=majordam_num1)
        source_data_withmajordam = GagesSource.choose_some_basins(self.config_data,
                                                                  self.config_data.model_dict["data"]["tRangeTrain"],
                                                                  screen_basin_area_huc4=False,
                                                                  major_dam_num=majordam_num2)
        sites_id_nomajordam = source_data_nomajordam.all_configs['flow_screen_gage_id']
        sites_id_withmajordam = source_data_withmajordam.all_configs['flow_screen_gage_id']
        idx_lst_nomajordam = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_nomajordam]
        idx_lst_withmajordam = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_withmajordam]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["no_major_dam", "major_dam"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_nomajordam])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_withmajordam])
        xs.append(x2)
        ys.append(y2)

        # 0: compare w/wo in conus ; 1: 0 + major dam with natflow; 2: 0 + seperate cases
        # compare_item = 0
        compare_item = 1
        # compare_item = 2
        if compare_item == 0:
            plot_ecdfs(xs, ys, cases_exps_legends_together)
        elif compare_item == 1:
            cases_exps = ["simulate_exp2", "storage_exp1", "storage_exp2", "storage_exp3"]
            cases_exps_legends_separate = ["major_dam_natflow", "major_dam_natflow_julian", "major_dam_natflow_storage",
                                           "major_dam_natflow_storage_seq2one"]
            for case_exp in cases_exps:
                config_data_i = load_dataconfig_case_exp(case_exp)
                pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
                pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
                obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
                inds_i = statError(obs_i, pred_i)
                x, y = ecdf(inds_i[keys_nse])
                xs.append(x)
                ys.append(y)
            plot_ecdfs(xs, ys, cases_exps_legends_together + cases_exps_legends_separate)

        elif compare_item == 2:
            cases_exps = ["nodam_exp3", "majordam_exp2"]
            cases_exps_legends_separate = ["no_major_dam", "major_dam"]
            for case_exp in cases_exps:
                config_data_i = load_dataconfig_case_exp(case_exp)
                pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
                pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
                obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
                inds_i = statError(obs_i, pred_i)
                x, y = ecdf(inds_i[keys_nse])
                xs.append(x)
                ys.append(y)

            plot_ecdfs(xs, ys, cases_exps_legends_together + cases_exps_legends_separate,
                       style=["together", "together", "separate", "separate"])

    def test_dor_seperate(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]
        dor_1 = - 0.02
        dor_2 = 0.02
        source_data_dor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_1)
        source_data_dor2 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          screen_basin_area_huc4=False,
                                                          DOR=dor_2)
        sites_id_dor1 = source_data_dor1.all_configs['flow_screen_gage_id']
        sites_id_dor2 = source_data_dor2.all_configs['flow_screen_gage_id']
        idx_lst_dor1 = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_dor1]
        idx_lst_dor2 = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_dor2]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["small_dor", "large_dor"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_dor1])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_dor2])
        xs.append(x2)
        ys.append(y2)

        # compare_item = 0
        compare_item = 1
        if compare_item == 0:
            plot_ecdfs(xs, ys, cases_exps_legends_together)
        elif compare_item == 1:
            cases_exps = ["dam_exp17", "dam_exp18"]
            cases_exps_legends_separate = ["small_dor", "large_dor"]
            for case_exp in cases_exps:
                config_data_i = load_dataconfig_case_exp(case_exp)
                pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
                pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
                obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
                inds_i = statError(obs_i, pred_i)
                x, y = ecdf(inds_i[keys_nse])
                xs.append(x)
                ys.append(y)

            plot_ecdfs(xs, ys, cases_exps_legends_together + cases_exps_legends_separate,
                       style=["together", "together", "separate", "separate"])

    def test_stor_seperate(self):
        data_model = GagesModel.load_datamodel(self.config_data.data_path["Temp"],
                                               data_source_file_name='test_data_source.txt',
                                               stat_file_name='test_Statistics.json',
                                               flow_file_name='test_flow.npy',
                                               forcing_file_name='test_forcing.npy',
                                               attr_file_name='test_attr.npy',
                                               f_dict_file_name='test_dictFactorize.json',
                                               var_dict_file_name='test_dictAttribute.json',
                                               t_s_dict_file_name='test_dictTimeSpace.json')
        all_sites = data_model.t_s_dict["sites_id"]
        storage_nor_1 = [0, 50]
        storage_nor_2 = [50, 15000]  # max is 14348.6581036888
        source_data_nor1 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          STORAGE=storage_nor_1)
        source_data_nor2 = GagesSource.choose_some_basins(self.config_data,
                                                          self.config_data.model_dict["data"]["tRangeTrain"],
                                                          STORAGE=storage_nor_2)
        sites_id_nor1 = source_data_nor1.all_configs['flow_screen_gage_id']
        sites_id_nor2 = source_data_nor2.all_configs['flow_screen_gage_id']
        idx_lst_nor1 = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_nor1]
        idx_lst_nor2 = [i for i in range(len(all_sites)) if all_sites[i] in sites_id_nor2]

        pred, obs = load_result(data_model.data_source.data_config.data_path['Temp'], self.test_epoch)
        pred = pred.reshape(pred.shape[0], pred.shape[1])
        obs = obs.reshape(pred.shape[0], pred.shape[1])
        inds = statError(obs, pred)
        inds_df = pd.DataFrame(inds)

        keys_nse = "NSE"
        xs = []
        ys = []
        cases_exps_legends_together = ["small_stor", "large_stor"]

        x1, y1 = ecdf(inds_df[keys_nse].iloc[idx_lst_nor1])
        xs.append(x1)
        ys.append(y1)

        x2, y2 = ecdf(inds_df[keys_nse].iloc[idx_lst_nor2])
        xs.append(x2)
        ys.append(y2)

        cases_exps = ["dam_exp12", "dam_exp11"]
        cases_exps_legends_separate = ["small_stor", "large_stor"]
        # cases_exps = ["dam_exp4", "dam_exp5", "dam_exp6"]
        # cases_exps = ["dam_exp1", "dam_exp2", "dam_exp3"]
        # cases_exps_legends = ["dam-lstm", "dam-with-natural-flow", "dam-with-kernel"]
        for case_exp in cases_exps:
            config_data_i = load_dataconfig_case_exp(case_exp)
            pred_i, obs_i = load_result(config_data_i.data_path['Temp'], self.test_epoch)
            pred_i = pred_i.reshape(pred_i.shape[0], pred_i.shape[1])
            obs_i = obs_i.reshape(obs_i.shape[0], obs_i.shape[1])
            inds_i = statError(obs_i, pred_i)
            x, y = ecdf(inds_i[keys_nse])
            xs.append(x)
            ys.append(y)

        plot_ecdfs(xs, ys, cases_exps_legends_together + cases_exps_legends_separate,
                   style=["together", "together", "separate", "separate"])


if __name__ == '__main__':
    unittest.main()
