#################################################
# to test if the arg-parse commands are correct

import os
import sys

sys.path.append("..")
import definitions
from data.config import default_config_file, cmd, update_cfg


def main(config_data, args):
    """
    Main function which is called from the command line. Entrypoint for training all ML models.
    """
    args.gage_id = ["01013500"]
    update_cfg(config_data, args)
    print("Process is now complete.")


# python script_args.py --sub test/exp1 --model_param {\"seq_length\":365\,\"n_time_series\":38} --continue_train 1 --weight_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/exp6/model.pth --download 0 --model_name KaiTlLSTM --opt Adadelta --loss_func RMSESum --hidden_size 256 --rs 1234 --cache_read 1 --cache_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/cache-328sites-20080101_20130101_20130101_20180101-30attr-8forcing --train_period 2008-01-01 2013-01-01 --test_period 2013-01-01 2018-01-01 --scaler DapengScaler --data_loader StreamflowDataModel --train_epoch 300 --save_epoch 50 --batch_size 100 --rho 365 --var_t pr rmin srad tmmn tmmx vs eto cet --var_t_type gridmet --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06 --n_feature 38 --gage_id 01013500 01022550
# python script_args.py --sub test/exp1 --model_param {\"seq_length\":365\,\"n_time_series\":38\,\"input_seq_len\":37\,\"output_seq_len\":1\,\"hidden_states\":256\,\"num_layers\":1\,\"bias\":true\,\"batch_size\":100\,\"probabilistic\":false} --continue_train 1 --weight_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/exp6/model.pth --download 0 --model_name KaiTlLSTM --opt Adadelta --loss_func RMSESum --hidden_size 256 --rs 1234 --cache_read 1 --cache_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/cache-328sites-20080101_20130101_20130101_20180101-30attr-8forcing --train_period 2008-01-01 2013-01-01 --test_period 2013-01-01 2018-01-01 --scaler DapengScaler --data_loader StreamflowDataModel --train_epoch 300 --save_epoch 50 --batch_size 100 --rho 365 --var_t pr rmin srad tmmn tmmx vs eto cet --var_t_type gridmet --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06 --n_feature 38 --gage_id 01013500 01022550
# python script_args.py --sub test/exp1 --weight_path_add {\"freeze_params\":[\"linearIn.bias\"\,\"linearIn.weight\"\,\"linearOut.bias\"\,\"linearOut.weight\"\,\"lstm.b_hh\"\,\"lstm.b_ih\"\,\"lstm.w_hh\"\,\"lstm.w_ih\"]} --model_param {\"seq_length\":365\,\"n_time_series\":38\,\"input_seq_len\":37\,\"output_seq_len\":1\,\"hidden_states\":256\,\"num_layers\":1\,\"bias\":true\,\"batch_size\":100\,\"probabilistic\":false} --continue_train 1 --weight_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/exp6/model.pth --download 0 --model_name KaiTlLSTM --opt Adadelta --loss_func RMSESum --hidden_size 256 --rs 1234 --cache_read 1 --cache_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/cache-328sites-20080101_20130101_20130101_20180101-30attr-8forcing --train_period 2008-01-01 2013-01-01 --test_period 2013-01-01 2018-01-01 --scaler DapengScaler --data_loader StreamflowDataModel --train_epoch 300 --save_epoch 50 --batch_size 100 --rho 365 --var_t pr rmin srad tmmn tmmx vs eto cet --var_t_type gridmet --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06 --n_feature 38 --gage_id 01013500 01022550
# python script_args.py --sub test/exp1 --model_param {\"seq_length\":365\,\"n_time_series\":38\,\"input_seq_len\":37\,\"output_seq_len\":1\,\"hidden_states\":256\,\"num_layers\":1\,\"bias\":true\,\"batch_size\":100\,\"probabilistic\":false} --continue_train 1 --weight_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/exp6/xxxmodel.pth --weight_path_add {\"freeze_params\":[\"linearIn.bias\"\,\"linearIn.weight\"\,\"linearOut.bias\"\,\"linearOut.weight\"\,\"lstm.b_hh\"\,\"lstm.b_ih\"\,\"lstm.w_hh\"\,\"lstm.w_ih\"]} --download 0 --model_name KaiTlLSTM --opt Adadelta --loss_func RMSESum --hidden_size 256 --rs 1234 --cache_read 1 --cache_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages_gridmet/cache-328sites-20080101_20130101_20130101_20180101-30attr-8forcing --train_period 2008-01-01 2013-01-01 --test_period 2013-01-01 2018-01-01 --scaler DapengScaler --data_loader StreamflowDataModel --train_epoch 300 --save_epoch 50 --batch_size 100 --rho 365 --var_t pr rmin srad tmmn tmmx vs eto cet --var_t_type gridmet --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06 --n_feature 38 --gage_id_file /mnt/data/owen411/code/hydro-spdb-dl/example/3557basins_ID_NSE_DOR.csv
# python script_args.py --sub test/exp1 --gage_id_file /mnt/data/owen411/code/hydro-spdb-dl/example/3557basins_ID_NSE_DOR.csv --download 0 --model_name DapengCNNLSTM --opt Adadelta --loss_func RMSESum --rs 1234 --model_param {\"n_kernel\":[10\,5]\,\"kernel_size\":[3\,3]\,\"stride\":[2\,1]\,\"nx\":37\,\"ny\":1\,\"nobs\":50\,\"hidden_size\":256\,\"dr\":0.5\,\"cnn_dr\":0.5\,\"cat_first\":true} --cache_write 1 --train_mode 0 --train_period 1990-01-01 2000-01-01 --test_period 2000-01-01 2010-01-01 --scaler DapengScaler --data_loader KernelFlowDataModel --train_epoch 300 --save_epoch 50 --batch_size 100 --rho 365 --var_o {\"RES_STOR_HIST\":{\"bins\":50}} --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06
# python script_args.py --sub test/exp1 --download 0 --train_mode 0 --model_name KaiTlLSTM --model_param {\"seq_length\":365\,\"n_time_series\":42\,\"input_seq_len\":37\,\"output_seq_len\":1\,\"hidden_states\":256\,\"num_layers\":1\,\"bias\":true\,\"batch_size\":100\,\"probabilistic\":false} --opt Adadelta --loss_func RMSESum --hidden_size 256 --rs 1234 --cache_write 1 --train_period 1990-01-01 2000-01-01 --test_period 2000-01-01 2010-01-01 --scaler DapengScaler --data_loader StreamflowDataModel --weight_path_add {\"freeze_params\":[\"linearIn.bias\"\,\"linearIn.weight\"\,\"linearOut.bias\"\,\"linearOut.weight\"\,\"lstm.b_hh\"\,\"lstm.b_ih\"\,\"lstm.w_hh\"\,\"lstm.w_ih\"]} --weight_path /mnt/data/owen411/code/hydro-spdb-dl/example/gages/exp2/05_April_202105_47AM_model.pth --continue_train 1 --train_epoch 300 --save_epoch 50 --var_c DRAIN_SQKM ELEV_MEAN_M_BASIN SLOPE_PCT DEVNLCD06 FORESTNLCD06 PLANTNLCD06 WATERNLCD06 SNOWICENLCD06 BARRENNLCD06 SHRUBNLCD06 GRASSNLCD06 WOODYWETNLCD06 EMERGWETNLCD06 AWCAVE PERMAVE RFACT ROCKDEPAVE GEOL_REEDBUSH_DOM GEOL_REEDBUSH_DOM_PCT STREAMS_KM_SQ_KM NDAMS_2009 STOR_NOR_2009 RAW_DIS_NEAREST_MAJ_DAM CANALS_PCT RAW_DIS_NEAREST_CANAL FRESHW_WITHDRAWAL POWER_SUM_MW PDEN_2000_BLOCK ROADS_KM_SQ_KM IMPNLCD06 DOR DAM_MAIN_PURPOSE DIVERSION DAM_GAGE_DIS_VAR DAM_STORAGE_STD --n_feature 42 --gage_id_file /mnt/data/owen411/code/hydro-spdb-dl/example/3557basins_ID_NSE_DOR.csv
if __name__ == '__main__':
    print("Begin\n")
    gages_dir = [os.path.join(definitions.DATASET_DIR, "gages_pro"),
                 os.path.join(definitions.DATASET_DIR, "gages"),
                 os.path.join(definitions.DATASET_DIR, "nid"),
                 os.path.join(definitions.DATASET_DIR, "gridmet")]
    dataset_name = "GAGES_PRO"
    config = default_config_file(gages_dir, dataset_name)
    cmd_args = cmd()
    main(config, cmd_args)
    print(config["model_params"])
    print("End\n")
