import os
import unittest
import numpy as np
import torch

import definitions
from data import GagesConfig
from data.data_config import add_model_param
from data.data_input import save_datamodel, GagesModel
from data.gages_input_dataset import GagesSimDataModel
from explore.stat import statError
from hydroDL.master.master import master_train_natural_flow, master_test_natural_flow
from utils.dataset_format import subset_of_dict
from visual import plot_ts_obs_pred
from visual.plot_model import plot_boxes_inds


class MyTestCase(unittest.TestCase):

    def setUp(self) -> None:
        """before all of these, natural flow model need to be generated by config.ini of gages dataset, and it need
        to be moved to right dir manually """
        config_dir = definitions.CONFIG_DIR
        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp1.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp1.ini")
        # self.subdir = "simulate/exp1"
        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp2.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp2.ini")
        # self.subdir = "simulate/exp2"
        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp3.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp3.ini")
        # self.subdir = "simulate/exp3"
        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp4.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp4.ini")
        # self.subdir = "simulate/exp4"

        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp5.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp5.ini")
        # self.subdir = "simulate/exp5"
        # self.sim_config_file = os.path.join(config_dir, "simulate/config_natureflow_1_exp6.ini")
        # self.config_file = os.path.join(config_dir, "simulate/config_natureflow_2_exp6.ini")
        # self.subdir = "simulate/exp6"
        self.sim_config_file = os.path.join(config_dir, "simulate/config1_exp10.ini")
        self.config_file = os.path.join(config_dir, "simulate/config2_exp10.ini")
        self.subdir = "simulate/exp10"
        self.config_data = GagesConfig.set_subdir(self.config_file, self.subdir)
        self.sim_config_data = GagesConfig.set_subdir(self.sim_config_file, self.subdir)
        add_model_param(self.config_data, "model", seqLength=7)
        # choose some small basins, unit: SQKM
        self.basin_area_screen = 100

    def test_gages_sim_data_model(self):
        quick_data_dir = os.path.join(self.config_data.data_path["DB"], "quickdata")
        sim_data_dir = os.path.join(quick_data_dir, "allref_85-05_nan-0.1_00-1.0")
        data_dir = os.path.join(quick_data_dir, "allnonref_85-05_nan-0.1_00-1.0")
        data_model1_train = GagesModel.load_datamodel(sim_data_dir,
                                                      data_source_file_name='data_source.txt',
                                                      stat_file_name='Statistics.json', flow_file_name='flow.npy',
                                                      forcing_file_name='forcing.npy', attr_file_name='attr.npy',
                                                      f_dict_file_name='dictFactorize.json',
                                                      var_dict_file_name='dictAttribute.json',
                                                      t_s_dict_file_name='dictTimeSpace.json')
        data_model2_train = GagesModel.load_datamodel(data_dir,
                                                      data_source_file_name='data_source.txt',
                                                      stat_file_name='Statistics.json', flow_file_name='flow.npy',
                                                      forcing_file_name='forcing.npy', attr_file_name='attr.npy',
                                                      f_dict_file_name='dictFactorize.json',
                                                      var_dict_file_name='dictAttribute.json',
                                                      t_s_dict_file_name='dictTimeSpace.json')
        data_model1_test = GagesModel.load_datamodel(sim_data_dir,
                                                     data_source_file_name='test_data_source.txt',
                                                     stat_file_name='test_Statistics.json',
                                                     flow_file_name='test_flow.npy',
                                                     forcing_file_name='test_forcing.npy',
                                                     attr_file_name='test_attr.npy',
                                                     f_dict_file_name='test_dictFactorize.json',
                                                     var_dict_file_name='test_dictAttribute.json',
                                                     t_s_dict_file_name='test_dictTimeSpace.json')
        data_model2_test = GagesModel.load_datamodel(data_dir,
                                                     data_source_file_name='test_data_source.txt',
                                                     stat_file_name='test_Statistics.json',
                                                     flow_file_name='test_flow.npy',
                                                     forcing_file_name='test_forcing.npy',
                                                     attr_file_name='test_attr.npy',
                                                     f_dict_file_name='test_dictFactorize.json',
                                                     var_dict_file_name='test_dictAttribute.json',
                                                     t_s_dict_file_name='test_dictTimeSpace.json')
        sim_gages_model_train = GagesModel.update_data_model(self.sim_config_data, data_model1_train)
        gages_model_train = GagesModel.update_data_model(self.config_data, data_model2_train)
        sim_gages_model_test = GagesModel.update_data_model(self.sim_config_data, data_model1_test)
        gages_model_test = GagesModel.update_data_model(self.config_data, data_model2_test)
        save_datamodel(sim_gages_model_train, "1", data_source_file_name='data_source.txt',
                       stat_file_name='Statistics.json', flow_file_name='flow', forcing_file_name='forcing',
                       attr_file_name='attr', f_dict_file_name='dictFactorize.json',
                       var_dict_file_name='dictAttribute.json', t_s_dict_file_name='dictTimeSpace.json')
        save_datamodel(sim_gages_model_test, "1", data_source_file_name='test_data_source.txt',
                       stat_file_name='test_Statistics.json', flow_file_name='test_flow',
                       forcing_file_name='test_forcing', attr_file_name='test_attr',
                       f_dict_file_name='test_dictFactorize.json', var_dict_file_name='test_dictAttribute.json',
                       t_s_dict_file_name='test_dictTimeSpace.json')
        save_datamodel(gages_model_train, "2", data_source_file_name='data_source.txt',
                       stat_file_name='Statistics.json', flow_file_name='flow', forcing_file_name='forcing',
                       attr_file_name='attr', f_dict_file_name='dictFactorize.json',
                       var_dict_file_name='dictAttribute.json', t_s_dict_file_name='dictTimeSpace.json')
        save_datamodel(gages_model_test, "2", data_source_file_name='test_data_source.txt',
                       stat_file_name='test_Statistics.json', flow_file_name='test_flow',
                       forcing_file_name='test_forcing', attr_file_name='test_attr',
                       f_dict_file_name='test_dictFactorize.json', var_dict_file_name='test_dictAttribute.json',
                       t_s_dict_file_name='test_dictTimeSpace.json')
        print("read and save data model")

    def test_train_gages_sim(self):
        with torch.cuda.device(1):
            # load model from npy data and then update some params for the test func
            data_model1 = GagesModel.load_datamodel(self.config_data.data_path["Temp"], "1",
                                                    data_source_file_name='data_source.txt',
                                                    stat_file_name='Statistics.json', flow_file_name='flow.npy',
                                                    forcing_file_name='forcing.npy', attr_file_name='attr.npy',
                                                    f_dict_file_name='dictFactorize.json',
                                                    var_dict_file_name='dictAttribute.json',
                                                    t_s_dict_file_name='dictTimeSpace.json')
            data_model1.update_model_param('train', nEpoch=300)
            data_model2 = GagesModel.load_datamodel(self.config_data.data_path["Temp"], "2",
                                                    data_source_file_name='data_source.txt',
                                                    stat_file_name='Statistics.json', flow_file_name='flow.npy',
                                                    forcing_file_name='forcing.npy', attr_file_name='attr.npy',
                                                    f_dict_file_name='dictFactorize.json',
                                                    var_dict_file_name='dictAttribute.json',
                                                    t_s_dict_file_name='dictTimeSpace.json')
            data_model = GagesSimDataModel(data_model1, data_model2)
            pre_trained_model_epoch = 160
            master_train_natural_flow(data_model, pre_trained_model_epoch)

    def test_test_gages_sim(self):
        with torch.cuda.device(1):
            data_model1 = GagesModel.load_datamodel(self.config_data.data_path["Temp"], "1",
                                                    data_source_file_name='test_data_source.txt',
                                                    stat_file_name='test_Statistics.json',
                                                    flow_file_name='test_flow.npy',
                                                    forcing_file_name='test_forcing.npy',
                                                    attr_file_name='test_attr.npy',
                                                    f_dict_file_name='test_dictFactorize.json',
                                                    var_dict_file_name='test_dictAttribute.json',
                                                    t_s_dict_file_name='test_dictTimeSpace.json')
            data_model2 = GagesModel.load_datamodel(self.config_data.data_path["Temp"], "2",
                                                    data_source_file_name='test_data_source.txt',
                                                    stat_file_name='test_Statistics.json',
                                                    flow_file_name='test_flow.npy',
                                                    forcing_file_name='test_forcing.npy',
                                                    attr_file_name='test_attr.npy',
                                                    f_dict_file_name='test_dictFactorize.json',
                                                    var_dict_file_name='test_dictAttribute.json',
                                                    t_s_dict_file_name='test_dictTimeSpace.json')
            model_input = GagesSimDataModel(data_model1, data_model2)
            pred, obs = master_test_natural_flow(model_input)
            pred = pred.reshape(pred.shape[0], pred.shape[1])
            obs = obs.reshape(pred.shape[0], pred.shape[1])

            inds = statError(obs, pred)
            show_me_num = 5
            t_s_dict = model_input.data_model2.t_s_dict
            sites = np.array(t_s_dict["sites_id"])
            # TODO: time been cut, so change it
            t_range = np.array(t_s_dict["t_final_range"])
            ts_fig = plot_ts_obs_pred(obs, pred, sites, t_range, show_me_num)
            ts_fig.savefig(os.path.join(self.config_data.data_path["Out"], "ts_fig.png"))
            # plot box，使用seaborn库
            keys = ["Bias", "RMSE", "NSE"]
            inds_test = subset_of_dict(inds, keys)
            box_fig = plot_boxes_inds(inds_test)
            box_fig.savefig(os.path.join(self.config_data.data_path["Out"], "box_fig.png"))


if __name__ == '__main__':
    unittest.main()
